### ISSUE TITLE
ClassNotFoundException with Kotlin 1.2.40

### ISSUE THREAD

**Issue by vRallev** [Takhion/kotlin-metadata#8]
In our Android project we're using Room and Room is internally using this library version `1.2.1`. With Kotlin `1.2.40` we're seeing this crash
```
e: [kapt] An exception occurred: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/serialization/jvm/JvmProtoBufUtil
        at me.eugeniomarletti.kotlin.metadata.KotlinClassMetadata$data$2.invoke(KotlinMetadata.kt:51)
        at me.eugeniomarletti.kotlin.metadata.KotlinClassMetadata$data$2.invoke(KotlinMetadata.kt:50)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at me.eugeniomarletti.kotlin.metadata.KotlinClassMetadata.getData(KotlinMetadata.kt)
        at android.arch.persistence.room.ext.KotlinMetadataProcessor$DefaultImpls.getParameterNames(KotlinMetadataProcessor.kt:33)
        at android.arch.persistence.room.processor.PojoProcessor.getParameterNames(PojoProcessor.kt:73)
        at android.arch.persistence.room.processor.PojoProcessor.getParamNames(PojoProcessor.kt:245)
        at android.arch.persistence.room.processor.PojoProcessor.chooseConstructor(PojoProcessor.kt:263)
        at android.arch.persistence.room.processor.PojoProcessor.doProcess(PojoProcessor.kt:207)
        at android.arch.persistence.room.processor.PojoProcessor.access$doProcess(PojoProcessor.kt:73)
        at android.arch.persistence.room.processor.PojoProcessor$process$1.invoke(PojoProcessor.kt:104)
        at android.arch.persistence.room.processor.PojoProcessor$process$1.invoke(PojoProcessor.kt:73)
        at android.arch.persistence.room.processor.cache.Cache$Bucket.get(Cache.kt:46)
        at android.arch.persistence.room.processor.PojoProcessor.process(PojoProcessor.kt:101)
        at android.arch.persistence.room.processor.PojoProcessor.processEmbeddedField(PojoProcessor.kt:396)
        at android.arch.persistence.room.processor.PojoProcessor.doProcess(PojoProcessor.kt:150)
        at android.arch.persistence.room.processor.PojoProcessor.access$doProcess(PojoProcessor.kt:73)
        at android.arch.persistence.room.processor.PojoProcessor$process$1.invoke(PojoProcessor.kt:104)
        at android.arch.persistence.room.processor.PojoProcessor$process$1.invoke(PojoProcessor.kt:73)
        at android.arch.persistence.room.processor.cache.Cache$Bucket.get(Cache.kt:46)
        at android.arch.persistence.room.processor.PojoProcessor.process(PojoProcessor.kt:101)
        at android.arch.persistence.room.processor.EntityProcessor.doProcess(EntityProcessor.kt:68)
        at android.arch.persistence.room.processor.EntityProcessor.access$doProcess(EntityProcessor.kt:50)
        at android.arch.persistence.room.processor.EntityProcessor$process$1.invoke(EntityProcessor.kt:57)
        at android.arch.persistence.room.processor.EntityProcessor$process$1.invoke(EntityProcessor.kt:50)
        at android.arch.persistence.room.processor.cache.Cache$Bucket.get(Cache.kt:46)
        at android.arch.persistence.room.processor.EntityProcessor.process(EntityProcessor.kt:56)
        at android.arch.persistence.room.processor.DatabaseProcessor.processEntities(DatabaseProcessor.kt:248)
        at android.arch.persistence.room.processor.DatabaseProcessor.doProcess(DatabaseProcessor.kt:63)
        at android.arch.persistence.room.processor.DatabaseProcessor.process(DatabaseProcessor.kt:53)
        at android.arch.persistence.room.RoomProcessor$DatabaseProcessingStep.process(RoomProcessor.kt:57)
        at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
        at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
        at org.jetbrains.kotlin.kapt3.ProcessorWrapper.process(annotationProcessing.kt:131)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
        at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:87)
        at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:45)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:257)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:212)
        at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:95)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:97)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:107)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:84)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:374)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:64)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:101)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:365)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:130)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:63)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:96)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:405)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:920)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:98)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:950)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:919)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:404)
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.serialization.jvm.JvmProtoBufUtil
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 83 more
```

I've tried to upgrade to version `1.3.0`, but the issue is still there. I used Gradle's dependency substitution feature for that, because the group ID has changed.
```
  configurations.all {
    resolutionStrategy.dependencySubstitution {
      all { DependencySubstitution dependency ->
        if (dependency.requested instanceof ModuleComponentSelector) {
          if (dependency.requested.group == 'me.eugeniomarletti' && dependency.requested.module == 'kotlin-metadata') {
            dependency.useTarget 'me.eugeniomarletti.kotlin.metadata:kotlin-metadata:1.3.0'
          }
        }
      }
    }
  }
```

**Comment by Takhion** [comment]
@vRallev have you tried forcing the dependency of [`compiler-embeddable`](https://github.com/Takhion/kotlin-metadata/blob/v1.3.0/lib/build.gradle.kts#L7) to be on a Kotlin version before `1.2.40`?

As mentioned on Slack: something was broken in Kotlin 1.2.40, luckily from the next version onwards `kotlin-metadata` won't have a direct dependency on the compiler anymore, and it won't break again :)

**Comment by TrevorSStone** [comment]
For anyone linked here having trouble getting this working you can place the following snippet in your base build.gradle file

```
subprojects {
    configurations.all {
        resolutionStrategy {
            eachDependency { DependencyResolveDetails details ->
                if (details.requested.name == 'kotlin-compiler-embeddable') {
                    details.useVersion "1.2.30"
                }
            }
        }
    }
}
```
If there is anything wrong with doing it this way please let me know!

**Comment by justjanne** [comment]
And here’s a version of @TrevorSStone ’s snippet that works in kotlin build scripts:

```kotlin
subprojects {
  configurations.all {
    resolutionStrategy {
      eachDependency {
        if (requested.name == "kotlin-compiler-embeddable") {
          useVersion("1.2.30")
        }
      }
    }
  }
}
```

(the differences being in Kotlin using `"` instead of `'` for strings, and eachDependency in Kotlin calling the closure on the details object instead of passing it as parameter)

**Comment by tasomaniac** [comment]
Just a note: Kotlin version above is simpler and works just fine in Groovy too.  `DependencyResolveDetails details ->` is redundant in Groovy.

**Comment by Takhion** [comment]
Fixed in [`v1.4.0`](https://github.com/Takhion/kotlin-metadata/releases/tag/v1.4.0) 🎉

**Comment by jemshit** [comment]
This getting same error on kotlin plugin 1.2.41 Android Studio 3.1.2. Do we still need to add[ this code ](https://github.com/ApplETS/Notre-Dame-Android/commit/39241a7a76714dce531e0f266282d529f1a5333e#diff-c197962302397baf3a4cc36463dce5eaR30)? @Takhion

**Comment by efemoney** [comment]
@jemshit It's not a Kotlin issue. The libraries (Room or Moshi-snapshot) that depend on kotlin-metadata have to update the dependency version to `1.4.0`. You will need to add that code for now.

**Comment by Takhion** [comment]
@efemoney @jemshit it is a Kotlin issue in the sense that they introduced a binary incompatibility in `compiler-embeddable`, but yes as an end result any library depending on that will break until either Kotlin fixes it or the library does!

For `kotlin-metadata`:
* if you're using it directly, just update to `1.4.0`
* if you're using a library that depends on it, use the workaround above until that library gets updated with `kotlin-metadata` version `1.4.0`

**Comment by michaelbarlow7** [comment]
If anyone (like me) ran into this issue with Room, as of May 2 it's been fixed in version `1.1.0-rc1`.

https://issuetracker.google.com/issues/78328708

**Comment by IgorGanapolsky** [comment]
I am getting the following build error in Android Studio:
> Could not find kotlin-metadata.jar (me.eugeniomarletti.kotlin.metadata:kotlin-metadata:1.4.0).
Searched in the following locations:
    https://jcenter.bintray.com/me/eugeniomarletti/kotlin/metadata/kotlin-metadata/1.4.0/kotlin-metadata-1.4.0.jar

I have no idea what causes it.  Does anybody know?

**Comment by Takhion** [comment]
@IgorGanapolsky are you still experiencing the build error? I know that yesterday jcenter was having some issues, maybe it was just a temporary thing on their side?

Otherwise, if you execute `./gradlew :myFailingProject:buildEnvironment` (replacing `:myFailingProject` with your failing project) what version of `kotlin-metadata` is resolved, and from what library?

**Comment by IgorGanapolsky** [comment]
@Takhion The issue went away after I deleted **~/.gradle/caches**.  It was a really strange error, since I wasn't using `kotlin-metadata` explicitly in any of my projects.

**Comment by a-kari** [comment]
I had the same issue in IntelliJ IDEA. It was because I've used a different `kotlin-reflect` version than `kotlin-gradle-plugin` version. Using the same version resolved the issue.
